# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '评论信息',
                'verbose_name_plural': '评论信息',
            },
        ),
        migrations.CreateModel(
            name='ItemInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('1', '爱心救助'), ('2', '公益众筹'), ('3', '梦想众筹')], max_length=20, verbose_name='项目类型')),
                ('item_name', models.CharField(max_length=20, verbose_name='项目名称')),
                ('funding_money', models.FloatField(default=0, verbose_name='已筹金额')),
                ('objective_money', models.FloatField(default=0, verbose_name='目标金额')),
                ('currency', models.CharField(choices=[('cny', '人民币'), ('vr', 'vr9')], max_length=5, verbose_name='币种')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发起时间')),
                ('total_time', models.IntegerField(default=0, verbose_name='项目时间')),
                ('left_time', models.IntegerField(default=0, verbose_name='剩余时间')),
                ('item_content', models.TextField(max_length=1000, verbose_name='项目内容')),
                ('fund_use', models.TextField(max_length=200, verbose_name='资金用途')),
                ('examination_status', models.CharField(choices=[('0', '未审核'), ('1', '进行中'), ('2', '审核未通过'), ('3', '已完成'), ('4', '已停止')], default='0', max_length=20, verbose_name='审核状态')),
                ('medias', models.CharField(max_length=1000, verbose_name='项目视频或图片地址')),
                ('recommand', models.CharField(default='0', max_length=5, verbose_name='推荐')),
                ('collect_users', models.ManyToManyField(related_name='collect_users', to='personal_center.MyUser', verbose_name='收藏者')),
                ('initiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiator_user', to='personal_center.MyUser', verbose_name='发起人')),
                ('support_users', models.ManyToManyField(related_name='suport_users', to='personal_center.MyUser', verbose_name='支持者')),
            ],
            options={
                'verbose_name': '项目信息',
                'verbose_name_plural': '项目信息',
            },
        ),
        migrations.CreateModel(
            name='PayBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(default=0, verbose_name='回报金额')),
                ('content', models.CharField(max_length=20, verbose_name='回报内容')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_content.ItemInfo', verbose_name='回报项目')),
            ],
        ),
        migrations.CreateModel(
            name='Thumb_up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_content.ItemInfo', verbose_name='项目')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_center.Order', verbose_name='订单')),
                ('support_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbs_support_user', to='personal_center.MyUser', verbose_name='支持者')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbs_user', to='personal_center.MyUser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '点赞信息',
                'verbose_name_plural': '点赞信息',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_content.ItemInfo', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='comment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_center.Order', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='comment',
            name='support_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_support_user', to='personal_center.MyUser', verbose_name='支持者'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commnet_user', to='personal_center.MyUser', verbose_name='用户'),
        ),
    ]
