# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_content', '0003_auto_20171113_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='type_name',
            field=models.CharField(max_length=20, verbose_name='类型名称'),
        ),
    ]
