# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_center', '0007_auto_20171117_1100'),
        ('project_content', '0004_auto_20171116_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('reason', models.CharField(max_length=200, verbose_name='举报理由')),
                ('images', models.CharField(max_length=200, verbose_name='举报图片')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_content.ItemInfo', verbose_name='项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_user', to='personal_center.MyUser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '举报信息',
                'verbose_name_plural': '举报信息',
            },
        ),
    ]
