# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_center', '0013_auto_20171127_1716'),
        ('project_content', '0006_auto_20171124_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
            ],
            options={
                'verbose_name': '快递公司',
                'verbose_name_plural': '快递公司',
            },
        ),
        migrations.CreateModel(
            name='UserPayBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', '待回报'), ('1', '已发货'), ('2', '已回报')], max_length=2, verbose_name='回报状态')),
                ('delivery_id', models.CharField(max_length=15, verbose_name='快递单号')),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_center.UserConsignee', verbose_name='回报地址')),
                ('delivery_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_content.DeliveryCompany', verbose_name='快递公司')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_center.Order', verbose_name='支持订单')),
                ('payback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_content.PayBack', verbose_name='回报内容')),
            ],
            options={
                'verbose_name': '用户回报',
                'verbose_name_plural': '用户回报',
            },
        ),
    ]
