# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_content', '0009_auto_20171128_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='up_comment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_content.Comment'),
        ),
        migrations.AlterField(
            model_name='iteminfo',
            name='examination_status',
            field=models.CharField(choices=[('0', '审核中'), ('1', '进行中'), ('2', '审核未通过'), ('3', '已完成'), ('4', '已停止')], default='0', max_length=20, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='userpayback',
            name='delivery_company',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='快递公司'),
        ),
    ]
