# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_content', '0010_auto_20171130_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayback',
            name='delete_status',
            field=models.CharField(default='0', max_length=2, verbose_name='订单状态'),
        ),
    ]
