# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_content', '0012_auto_20171201_1127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
