# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_content', '0013_delete_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='type_log',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='类型图标'),
        ),
    ]
