# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-18 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_content', '0016_auto_20171214_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminfo',
            name='examination_time',
            field=models.DateTimeField(null=True, verbose_name='发起时间'),
        ),
    ]
