# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-14 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_project', '0004_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(max_length=20, verbose_name='手续费类型')),
                ('fee_money', models.FloatField(default=0, verbose_name='手续费用')),
            ],
            options={
                'verbose_name': '手续费',
                'verbose_name_plural': '手续费',
            },
        ),
    ]
