# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 06:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelperInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('ID_card', models.CharField(max_length=18, verbose_name='身份证号')),
                ('disease', models.CharField(max_length=50, verbose_name='所患疾病')),
                ('hospital', models.CharField(max_length=50, verbose_name='医院')),
                ('details', models.CharField(max_length=50, verbose_name='项目详情')),
                ('medical_certificate', models.FileField(max_length=50, upload_to='medical_certificate/%Y/%m', verbose_name='诊断书')),
                ('relationship', models.FileField(max_length=50, upload_to='relationship/%Y/%m', verbose_name='关系证明')),
                ('property_status', models.FileField(max_length=50, upload_to='property_status/%Y/%m', verbose_name='财产状况')),
                ('car_status', models.FileField(max_length=50, upload_to='car_status/%Y/%m', verbose_name='汽车状况')),
                ('medical_insurance', models.FileField(max_length=50, upload_to='medical_insurance/%Y/%m', verbose_name='医保状况')),
                ('pledge_cards', models.FileField(max_length=50, upload_to='pledge_cards/%Y/%m', verbose_name='承诺书')),
                ('image_show0', models.ImageField(blank=True, max_length=50, null=True, upload_to='image_show/%Y/%m', verbose_name='图片展示0')),
                ('image_show1', models.ImageField(blank=True, max_length=50, null=True, upload_to='image_show/%Y/%m', verbose_name='图片展示1')),
                ('image_show2', models.ImageField(blank=True, max_length=50, null=True, upload_to='image_show/%Y/%m', verbose_name='图片展示2')),
                ('image_show3', models.ImageField(blank=True, max_length=50, null=True, upload_to='image_show/%Y/%m', verbose_name='图片展示3')),
                ('image_show4', models.ImageField(blank=True, max_length=50, null=True, upload_to='image_show/%Y/%m', verbose_name='图片展示4')),
                ('image_show5', models.ImageField(blank=True, max_length=50, null=True, upload_to='image_show/%Y/%m', verbose_name='图片展示5')),
            ],
            options={
                'verbose_name': '求助人资料证明',
                'verbose_name_plural': '求助人资料证明',
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unionid', models.CharField(help_text='unionId', max_length=200, null=True)),
                ('openid', models.CharField(help_text='用户openid', max_length=64)),
                ('role', models.IntegerField(default=0)),
                ('about_me', models.TextField(default='这个人很懒，什么都没有留下。', help_text='个性签名')),
                ('avatar_url', models.CharField(help_text='用户头像', max_length=300, null=True)),
                ('nick_name', models.CharField(help_text='用户昵称', max_length=300, null=True)),
                ('join_date', models.DateTimeField(default=datetime.datetime(2017, 11, 7, 14, 56, 18, 76665), help_text='加入时间')),
                ('last_login', models.DateTimeField(default=datetime.datetime(2017, 11, 7, 14, 56, 18, 76727), help_text='上次登录')),
                ('real_name', models.CharField(help_text='真实姓名', max_length=8, null=True)),
                ('mobile', models.CharField(help_text='手机号', max_length=32, null=True)),
                ('sex', models.CharField(help_text='性别', max_length=4, null=True)),
                ('age', models.IntegerField(default=0, help_text='年龄', null=True)),
                ('id_card', models.CharField(help_text='身份证', max_length=32, null=True)),
                ('address', models.CharField(help_text='地址', max_length=64, null=True)),
                ('balance', models.IntegerField(default=0, help_text='钱包余额')),
                ('state', models.IntegerField(default=0, help_text='0:开启；1：禁用')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='订单号')),
                ('item_id', models.CharField(max_length=20, verbose_name='项目id')),
                ('support_money', models.FloatField(default=0, verbose_name='支持金额')),
                ('trade_time', models.DateTimeField(auto_now_add=True, verbose_name='交易时间')),
                ('trade_method', models.CharField(choices=[('0', '支付宝支付'), ('1', '微信支付'), ('2', '国付宝支付'), ('3', '交易宝支付')], max_length=1, verbose_name='交易方式')),
                ('trade_result', models.CharField(choices=[('0', '交易失败'), ('1', '交易成功')], max_length=1, verbose_name='交易结果')),
                ('payback', models.CharField(max_length=10, verbose_name='是否接收产品回报')),
                ('delivery_status', models.CharField(choices=[('0', '待支付'), ('1', '待发货'), ('2', '待收货'), ('3', '待评价'), ('4', '退款')], max_length=1, verbose_name='发货状态')),
                ('consignee_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='收货人姓名')),
                ('consignee_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='收货人电话')),
                ('consignee_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='收货人地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_center.MyUser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='RedPacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_status', models.CharField(choices=[('0', '未使用'), ('1', '已过期'), ('2', '已使用')], max_length=1, verbose_name='使用状态')),
                ('money', models.IntegerField(verbose_name='价值')),
            ],
            options={
                'verbose_name': '红包',
                'verbose_name_plural': '红包',
            },
        ),
    ]
