# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 08:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConsignee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignee_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='收货人姓名')),
                ('consignee_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='收货人电话')),
                ('consignee_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='收货人地址')),
            ],
        ),
        migrations.AlterField(
            model_name='myuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 16, 37, 24, 994913), help_text='加入时间'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 16, 37, 24, 994957), help_text='上次登录'),
        ),
        migrations.AddField(
            model_name='userconsignee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_center.MyUser', verbose_name='用户'),
        ),
    ]
