# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 08:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_center', '0002_auto_20171108_1637'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelperInfo',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 13, 16, 56, 18, 607942), help_text='加入时间'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 13, 16, 56, 18, 607987), help_text='上次登录'),
        ),
    ]
