# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 06:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_center', '0007_auto_20171117_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconsignee',
            name='consignee_region',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='地区信息'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 17, 14, 17, 12, 490290), help_text='加入时间'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 17, 14, 17, 12, 490335), help_text='上次登录'),
        ),
    ]
