# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 06:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_center', '0008_auto_20171117_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='certification',
            field=models.CharField(choices=[('0', '未认证'), ('1', '已认证')], default='0', max_length=2, verbose_name='实名认证'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 14, 56, 7, 968214), help_text='加入时间'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 14, 56, 7, 968259), help_text='上次登录'),
        ),
    ]
