# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 05:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_center', '0009_auto_20171120_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='password',
            field=models.CharField(max_length=8, null=True, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 13, 49, 7, 485841), help_text='加入时间'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 13, 49, 7, 485886), help_text='上次登录'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='mobile',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='手机号'),
        ),
    ]
