# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 06:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_center', '0010_auto_20171122_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userconsignee',
            options={'verbose_name': '收获地址', 'verbose_name_plural': '收获地址'},
        ),
        migrations.AddField(
            model_name='myuser',
            name='day_score',
            field=models.IntegerField(default=0, verbose_name='日积分'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='month_score',
            field=models.IntegerField(default=0, verbose_name='月积分'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='score',
            field=models.IntegerField(default=0, verbose_name='积分'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='week_score',
            field=models.IntegerField(default=0, verbose_name='周积分'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='about_me',
            field=models.TextField(default='这个人很懒，什么都没有留下。', verbose_name='个性签名'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='address',
            field=models.CharField(max_length=64, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='age',
            field=models.IntegerField(default=0, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='avatar_url',
            field=models.CharField(max_length=300, null=True, verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='钱包余额'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='id_card',
            field=models.CharField(max_length=32, null=True, verbose_name='身份证'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 14, 27, 20, 471600), verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 14, 27, 20, 471718), verbose_name='上次登录'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='nick_name',
            field=models.CharField(max_length=300, null=True, verbose_name='用户昵称'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='openid',
            field=models.CharField(max_length=64, verbose_name='用户openid'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='sex',
            field=models.CharField(max_length=4, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='state',
            field=models.IntegerField(default=0, verbose_name='0:开启；1：禁用'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='unionid',
            field=models.CharField(max_length=200, null=True, verbose_name='unionId'),
        ),
    ]
