# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 07:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_center', '0017_auto_20171130_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 30, 15, 45, 42, 501313), verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 30, 15, 45, 42, 501435), verbose_name='上次登录'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('0', '待支付'), ('1', '待发货'), ('2', '已发货'), ('3', '待评价'), ('4', '退款')], max_length=1, verbose_name='发货状态'),
        ),
    ]
