# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 03:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_center', '0018_auto_20171130_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 1, 11, 27, 16, 345195), verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 1, 11, 27, 16, 345324), verbose_name='上次登录'),
        ),
    ]
