# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 06:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_center', '0019_auto_20171201_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='银行名称')),
            ],
        ),
        migrations.CreateModel(
            name='BankCardInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=50, verbose_name='银行')),
                ('card_no', models.CharField(max_length=19, verbose_name='卡号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('id_no', models.CharField(max_length=32, verbose_name='身份证号')),
                ('phone', models.CharField(max_length=32, verbose_name='手机号码')),
            ],
        ),
        migrations.AlterField(
            model_name='myuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 1, 14, 47, 7, 410840), verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 1, 14, 47, 7, 410905), verbose_name='上次登录'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='banks',
            field=models.ManyToManyField(to='personal_center.BankCardInfo', verbose_name='银行卡'),
        ),
    ]
