# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 09:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_center', '0020_auto_20171201_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='log',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='标志'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 1, 17, 7, 41, 512528), verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 1, 17, 7, 41, 512595), verbose_name='上次登录'),
        ),
    ]
