# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 09:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_center', '0021_auto_20171201_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcardinfo',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal_center.Bank', verbose_name='银行'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 1, 17, 37, 47, 438034), verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 1, 17, 37, 47, 438092), verbose_name='上次登录'),
        ),
    ]
