# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 01:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_center', '0022_auto_20171201_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 7, 9, 50, 46, 875865), verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 7, 9, 50, 46, 875928), verbose_name='上次登录'),
        ),
        migrations.AlterField(
            model_name='order',
            name='trade_method',
            field=models.CharField(choices=[('0', '支付宝支付'), ('1', '微信支付'), ('2', '国付宝支付'), ('3', '交易宝支付')], default='1', max_length=1, verbose_name='交易方式'),
        ),
        migrations.AlterField(
            model_name='order',
            name='trade_result',
            field=models.CharField(choices=[('0', '交易失败'), ('1', '交易成功')], default='0', max_length=1, verbose_name='交易结果'),
        ),
    ]
