# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 05:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_center', '0024_auto_20171207_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 7, 13, 46, 7, 757921), verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 7, 13, 46, 7, 758000), verbose_name='上次登录'),
        ),
    ]
