# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 08:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_center', '0025_auto_20171207_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 7, 16, 2, 26, 905432), verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 7, 16, 2, 26, 905510), verbose_name='上次登录'),
        ),
    ]
