# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 07:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personal_center', '0027_auto_20171211_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='注册时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 12, 15, 24, 12, 218752), verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 12, 15, 24, 12, 218932), verbose_name='上次登录'),
        ),
    ]
