# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-15 09:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_center', '0032_auto_20171214_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_before', models.FloatField(default=0, verbose_name='交易前金额')),
                ('money_now', models.FloatField(default=0, verbose_name='交易后金额')),
                ('balance', models.FloatField(default=0, verbose_name='交易金额')),
                ('trade_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='交易类型')),
                ('trade_time', models.DateTimeField(auto_now_add=True, verbose_name='交易时间')),
                ('trade_status', models.CharField(default='wait_check', max_length=20, verbose_name='交易状态')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_center.BankCardInfo', verbose_name='银行卡信息')),
            ],
        ),
        migrations.AlterField(
            model_name='myuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 15, 17, 45, 43, 848776), verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 15, 17, 45, 43, 848958), verbose_name='上次登录'),
        ),
        migrations.AddField(
            model_name='traderecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_center.MyUser', verbose_name='用户'),
        ),
    ]
