# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 05:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_center', '0034_auto_20171215_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcardinfo',
            name='bank',
            field=models.CharField(default='', max_length=50, verbose_name='银行'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 21, 13, 19, 13, 558286), verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 21, 13, 19, 13, 558332), verbose_name='上次登录'),
        ),
    ]
