# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-27 09:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_center', '0035_auto_20171221_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcardinfo',
            name='card_no',
            field=models.CharField(max_length=19, unique=True, verbose_name='卡号'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 27, 17, 56, 45, 999638), verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 27, 17, 56, 45, 999697), verbose_name='上次登录'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payback',
            field=models.CharField(default='0', max_length=10, verbose_name='是否接收产品回报'),
        ),
    ]
