# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-15 06:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_center', '0036_auto_20171227_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='birthday',
            field=models.CharField(max_length=64, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 15, 14, 43, 32, 43677), verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 15, 14, 43, 32, 43758), verbose_name='上次登录'),
        ),
    ]
