# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-15 08:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_center', '0037_auto_20180115_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='normal', max_length=50, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 15, 16, 16, 59, 960494), verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 15, 16, 16, 59, 960745), verbose_name='上次登录'),
        ),
    ]
