# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-18 06:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_center', '0038_auto_20180115_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 18, 14, 15, 58, 613099), verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 18, 14, 15, 58, 613180), verbose_name='上次登录'),
        ),
    ]
